<a href="https://colab.research.google.com/github/hanene2030/numpy/blob/main/10_advanced_linear_algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Advanced linear

In [1]:
import numpy as np
from numpy import linalg

In [2]:
#Finding eigenvalues and eigenvectors

In [4]:
rng = np.random.default_rng()
matrix = rng.random(9).reshape(3,3)
matrix


array([[0.05472122, 0.1479933 , 0.24385678],
       [0.15678262, 0.16136628, 0.5320602 ],
       [0.65656018, 0.43678657, 0.94739909]])

In [7]:
eigenvalues , eigenvectors = linalg.eig(matrix)
#eigenvalue, eigenvector

In [10]:
eigenvectors.shape

(3, 3)

In [11]:
eigenvalues.shape


(3,)

In [14]:
#determinant
linalg.det(matrix)#Non zero =>the matrix is invertable

0.01622842235558521

In [15]:
print("product of eigenvalues" , np.prod(eigenvalues))

product of eigenvalues (0.016228422355585238+0j)


#Types of matrices

In [19]:
#Diagonal matrix if the only non-zero entries are on the diagonal
D = np.array([[2,0],[0,5]])
D


array([[2, 0],
       [0, 5]])

In [20]:
identity_matrix = np.eye(3)
identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
np.diag([5 , 5 , 6 , 7])

array([[5, 0, 0, 0],
       [0, 5, 0, 0],
       [0, 0, 6, 0],
       [0, 0, 0, 7]])

In [24]:
#Orthogonal matrix =>if the columns are orthogonal and each column have lengh one
O = np.array([[1/(2 ** (1/2)), 1/(2 ** (1/2))],[1/(2 ** (1/2)) , -1/(2 ** (1/2))]])
O

array([[ 0.70710678,  0.70710678],
       [ 0.70710678, -0.70710678]])

In [26]:
#Check that O is orthogonal
np.dot(O[:,0], O[:,1]) , linalg.norm(O[:,0]) , linalg.norm(O[:,1])

(0.0, 0.9999999999999999, 0.9999999999999999)

In [27]:
# caluclate the inverse =>is the transpose in this case  =>always non zero determinant
# x o = y => x = o^-1 y 
y = np.array([4, 5])
x = O.transpose() @ y
x



array([ 6.36396103, -0.70710678])

In [28]:
# Upper triangular matrices 

In [30]:
R = np.array([[1 , 2], [0, 3]])
R# all the entries belw the diagonal are zeros

array([[1, 2],
       [0, 3]])

In [31]:
#The determinant in this case is easy to calculate => the product of the diag elements
linalg.det(R)


3.0000000000000004

In [ ]:
#Solving linear system is quick



In [33]:
#QR decomposition =>Any matrix = QR (Q is orthogonal, R is uppare triangle)

In [34]:
A = np.array([[1, 2], [3, 4]])

In [36]:
q, r = linalg.qr(A)

In [37]:
q

array([[-0.31622777, -0.9486833 ],
       [-0.9486833 ,  0.31622777]])

In [38]:
r

array([[-3.16227766, -4.42718872],
       [ 0.        , -0.63245553]])

In [40]:
np.dot(q[:,0], q[:,1]) , linalg.norm(q[:,0]) , linalg.norm(q[:,1])

(0.0, 1.0, 1.0)

In [41]:
q @ r

array([[1., 2.],
       [3., 4.]])

In [43]:
# to compare matrices
if np.allclose(A, q @ r):
  print("Great work")

Great work


In [44]:
# A =QR is invertible when none of the entries on the diag of R is zero

# When systems of equations are not solvable 

In [48]:
A = np.array([[1, 1], [1, 1]])
A

array([[1, 1],
       [1, 1]])

In [49]:
y = np.array([3, 5])

In [50]:
#Solve Ax = y

In [52]:
#x = linalg.solve(A , y)

In [53]:
# How to failsafe the code
from numpy.linalg import LinAlgError


In [54]:
try:
  x = linalg.solve(A , y)
  if not np.allclose(A @ x , y):
    raise LinAlgError
  print("The solution is given by x = ", x)
except LinAlgError:
  print("The solution does not exist")


The solution does not exist


In [58]:
# if there is no x, we can find x that ax is close to y
#least square
res = linalg.lstsq(A, y, rcond=None)
res

(array([2., 2.]), array([], dtype=float64), 1, array([2., 0.]))

In [59]:
x = res[0]

In [61]:
print("The best solution \n", x)

The best solution 
 [2. 2.]


In [64]:
A @ x

array([4., 4.])

In [65]:
y

array([3, 5])