<a href="https://colab.research.google.com/github/hanene2030/numpy/blob/main/1_vectors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Worknig with vectors


## Creating vectors & extracting values

In [ ]:
import numpy as np
list_of_nums =[4, 8, 6, 8]
array = np.array(list_of_nums)
print(type(array), type(list_of_nums))

<class 'numpy.ndarray'> <class 'list'>


In [ ]:
# Extracting values
print(array[-1])

8


In [ ]:
#Setting value
array[-1]= 4
array

array([4, 8, 6, 4])

In [ ]:
# Creating vectors with np.arange 

In [ ]:
squential_numbers = np.arange(1, 2, 0.1)
squential_numbers

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9])

In [ ]:
squential_numbers2 = np.arange(20)
squential_numbers2 # Not included 20

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
squential_numbers3 = np.arange(20, 40)
squential_numbers3 # Not included 40, included 20

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39])

## Basic operations

In [ ]:
first = np.arange(4, 10)
second = np.arange(10, 16)
#print(first.shape, second.shape)
#Addition
summation = first + second
print(first, "  +  ", second, "     =      ",summation)


[4 5 6 7 8 9]   +   [10 11 12 13 14 15]      =       [14 16 18 20 22 24]


In [ ]:
# With list + is equal to concat
list1 = [1, 2]
list2 = [2, 3]
print(list1+ list2 )

[1, 2, 2, 3]


In [ ]:
#Substraction
substraction = first - second
print(first, "  -  ", second, "     =      ",substraction)

[4 5 6 7 8 9]   -   [10 11 12 13 14 15]      =       [-6 -6 -6 -6 -6 -6]


In [ ]:
#Multiplication
multiplication = first * second
print(first, "  *  ", second, "     =      ",multiplication)

[4 5 6 7 8 9]   *   [10 11 12 13 14 15]      =       [ 40  55  72  91 112 135]


In [ ]:
#Division
division = np.around(first / second ,2 )# round fnct doesnt work with np array , use np.around
print(first, "  /  ", second, "     =      ",division)

[4 5 6 7 8 9]   /   [10 11 12 13 14 15]      =       [0.4  0.45 0.5  0.54 0.57 0.6 ]


In [ ]:
#Exponentiation
exponentiation = first ** second
print(first, "  **  ", second, "     =      ",exponentiation)

[4 5 6 7 8 9]   **   [10 11 12 13 14 15]      =       [        1048576        48828125      2176782336     96889010407
   4398046511104 205891132094649]


In [ ]:
np.array([2, 4]) ** np.array([1, 2]) 

array([ 2, 16])

## Numpy datatypes

In [ ]:
#What datatypes does numpy have=> NumPy supports a much greater variety of numerical types than Python does ,Source:
#https://numpy.org/doc/stable/user/basics.types.html
array = np.arange(20)
array.dtype

dtype('int64')

In [ ]:
array = np.array([1, 2, 3], dtype=np.float16 )
array.dtype

dtype('float16')

In [ ]:
array = np.array([10, 20, 53], dtype=np.int8 )
array.dtype

dtype('int8')

In [ ]:
array + 100

array([ 110,  120, -103], dtype=int8)

In [ ]:
#Size of a vector
array.size

3

In [ ]:
len(array) # better to use size attribute

3

In [ ]:
#  access number of bytes that have been used
array = np.array([10, 20, 53], dtype=np.int32 )
array.nbytes, array.size


(12, 3)

## Slicing 

In [ ]:
array = np.array(["1", "4", "10", "20", "30", "34"])
# take everithing after a specific index
array[3:] , array[:], array[1:] , array[100:]

(array(['20', '30', '34'], dtype='<U2'),
 array(['1', '4', '10', '20', '30', '34'], dtype='<U2'),
 array(['4', '10', '20', '30', '34'], dtype='<U2'),
 array([], dtype='<U2'))

In [ ]:
# everithing before an array
array[:3], array[:100] 

(array(['1', '4', '10'], dtype='<U2'),
 array(['1', '4', '10', '20', '30', '34'], dtype='<U2'))

In [ ]:
#in between indexes
array[3:5] # exclude the 5th

array(['20', '30'], dtype='<U2')

In [ ]:
#negative indexes
array[2:-2]

array(['10', '20'], dtype='<U2')

In [ ]:
array[0:-1] ,  array

(array(['1', '4', '10', '20', '30'], dtype='<U2'),
 array(['1', '4', '10', '20', '30', '34'], dtype='<U2'))

In [ ]:
array[2:5] , array[2:5:2] # jump

(array(['10', '20', '30'], dtype='<U2'), array(['10', '30'], dtype='<U2'))

In [ ]:
#Lets reverse an array
reverse_array = array[::-1]
reverse_array

array(['34', '30', '20', '10', '4', '1'], dtype='<U2')

## Sorting

In [ ]:
#2 ways to sort things in numpy
array = np.array([3, 45, 1 , 50 , 20])

In [ ]:
# 1 sort in place
array.sort()
array

array([ 1,  3, 20, 45, 50])

In [ ]:
# 2 np.sort funct =>Return a sorted array
array = np.array([3, 45, 1 , 50 , 20])
np.sort(array , kind="heapsort") , array

(array([ 1,  3, 20, 45, 50]), array([ 3, 45,  1, 50, 20]))

## Copies vs Views

In [ ]:
#Reverse an array
array = np.array([3, 45, 1 , 50 , 20])
reverse_array = array[::-1]
reverse_array[0] = 100
reverse_array , array  #==>Slicing is creating a view

(array([100,  50,   1,  45,   3]), array([  3,  45,   1,  50, 100]))

In [ ]:
#Make array positive
array = np.array([-23, 45, 1 , 50 , 20])
positive_array = np.abs(array) 
positive_array[0] =200
positive_array , array #=>It hasnt affected the original one ==>nb.abs created a copy

(array([200,  45,   1,  50,  20]), array([-23,  45,   1,  50,  20]))

## Aggregate function  

In [ ]:
array = np.array([-23, 45, 1 , 50 , 20])
#all the fntc that an array does has 
#print(dir(array))
sum_of_array = np.sum(array)
sum_of_array

93

In [ ]:
mean_of_array = np.mean(array)
mean_of_array

18.6

In [ ]:
product_of_array = np.prod(array)
product_of_array

-1035000

In [ ]:
#Find max and min
np.max(array), np.min(array)

(50, -23)

In [ ]:
#Argmax and Argmin fnct ==>max &min index
np.argmax(array), np.argmin(array)

(3, 0)