<a href="https://colab.research.google.com/github/hanene2030/numpy/blob/main/4_making_modifying_matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Making modifying matrices

In [ ]:
import numpy as np
my_list = [[1,12,3],
           [23,4,5],
           [31,12,6]]

In [ ]:
matrix = np.array(my_list)
matrix

array([[ 1, 12,  3],
       [23,  4,  5],
       [31, 12,  6]])

In [ ]:
type(matrix)

numpy.ndarray

In [ ]:
vector = np.arange(5)

In [ ]:
list(vector)

[0, 1, 2, 3, 4]

In [ ]:
list(matrix)

[array([ 1, 12,  3]), array([23,  4,  5]), array([31, 12,  6])]

In [ ]:
type(list(matrix))

list

In [ ]:
matrix.tolist()

[[1, 12, 3], [23, 4, 5], [31, 12, 6]]

In [ ]:
vector.tolist()

[0, 1, 2, 3, 4]

In [ ]:
matrix


array([[ 1, 12,  3],
       [23,  4,  5],
       [31, 12,  6]])

In [ ]:
matrix[1]

array([23,  4,  5])

In [ ]:
matrix[1] = np.array([2,5,6])

In [ ]:
matrix


array([[ 1, 12,  3],
       [ 2,  5,  6],
       [31, 12,  6]])

In [ ]:
matrix[2][1] = 10

In [ ]:
matrix

array([[ 1, 12,  3],
       [ 2,  5,  6],
       [31, 10,  6]])

In [ ]:
matrix[2,1]=200

In [ ]:
matrix

array([[  1,  12,   3],
       [  2,   5,   6],
       [ 31, 200,   6]])

In [ ]:
matrix[1:]

array([[  2,   5,   6],
       [ 31, 200,   6]])

In [ ]:
matrix[:,2]

array([3, 6, 6])

In [ ]:
matrix[:,1]#:, =>take all the rows

array([ 12,   5, 200])

In [ ]:
my_matrix = np.array([[1, 4, 5], [10, 13, 9], [10, 8, 5]])
my_matrix

array([[ 1,  4,  5],
       [10, 13,  9],
       [10,  8,  5]])

In [ ]:
# Find first column
first_column = my_matrix[:,0]
first_column

array([ 1, 10, 10])

In [ ]:
# Find third row
third_row = my_matrix[2:3]
third_row

array([[10,  8,  5]])

## Attributes

In [ ]:
matrix.ndim, vector.ndim

(2, 1)

In [ ]:
matrix.dtype, vector.dtype

(dtype('int64'), dtype('int64'))

In [ ]:
matrix.size, vector.size

(9, 5)

In [ ]:
matrix.shape, vector.shape

((3, 3), (5,))

In [ ]:
matrix.shape[0]
# matrix.shape[0] = 1 => error /cannot be asigned because it is a triple 

3

In [ ]:
row_vec = vector[np.newaxis, :]
row_vec

array([[0, 1, 2, 3, 4]])

In [ ]:
row_vec.shape

(1, 5)

In [ ]:
col_vec = vector[ :, np.newaxis]
col_vec

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [ ]:
col_vec[:,0]

array([0, 1, 2, 3, 4])

In [ ]:
row_vec[0]

array([0, 1, 2, 3, 4])

## Changing the shape

In [ ]:
 #create the matrix containing all the numbers from one to 100/ t in a 10 by 10 grid
 vector = np.arange(1, 101) 
 vector

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [ ]:
matrix = vector.reshape(10,10)
matrix

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [ ]:
matrix.reshape(100)

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [ ]:
#it is a view and not a new matrix
matrix[0,0] = 1000
vector [0]

1000

In [ ]:
matrix.reshape(50,2), matrix.reshape(2,50)

(array([[1000,    2],
        [   3,    4],
        [   5,    6],
        [   7,    8],
        [   9,   10],
        [  11,   12],
        [  13,   14],
        [  15,   16],
        [  17,   18],
        [  19,   20],
        [  21,   22],
        [  23,   24],
        [  25,   26],
        [  27,   28],
        [  29,   30],
        [  31,   32],
        [  33,   34],
        [  35,   36],
        [  37,   38],
        [  39,   40],
        [  41,   42],
        [  43,   44],
        [  45,   46],
        [  47,   48],
        [  49,   50],
        [  51,   52],
        [  53,   54],
        [  55,   56],
        [  57,   58],
        [  59,   60],
        [  61,   62],
        [  63,   64],
        [  65,   66],
        [  67,   68],
        [  69,   70],
        [  71,   72],
        [  73,   74],
        [  75,   76],
        [  77,   78],
        [  79,   80],
        [  81,   82],
        [  83,   84],
        [  85,   86],
        [  87,   88],
        [  89,   90],
        [ 

In [ ]:
matrix.reshape(10,-1)

array([[1000,    2,    3,    4,    5,    6,    7,    8,    9,   10],
       [  11,   12,   13,   14,   15,   16,   17,   18,   19,   20],
       [  21,   22,   23,   24,   25,   26,   27,   28,   29,   30],
       [  31,   32,   33,   34,   35,   36,   37,   38,   39,   40],
       [  41,   42,   43,   44,   45,   46,   47,   48,   49,   50],
       [  51,   52,   53,   54,   55,   56,   57,   58,   59,   60],
       [  61,   62,   63,   64,   65,   66,   67,   68,   69,   70],
       [  71,   72,   73,   74,   75,   76,   77,   78,   79,   80],
       [  81,   82,   83,   84,   85,   86,   87,   88,   89,   90],
       [  91,   92,   93,   94,   95,   96,   97,   98,   99,  100]])

In [ ]:
matrix.reshape(-1)

array([1000,    2,    3,    4,    5,    6,    7,    8,    9,   10,   11,
         12,   13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
         23,   24,   25,   26,   27,   28,   29,   30,   31,   32,   33,
         34,   35,   36,   37,   38,   39,   40,   41,   42,   43,   44,
         45,   46,   47,   48,   49,   50,   51,   52,   53,   54,   55,
         56,   57,   58,   59,   60,   61,   62,   63,   64,   65,   66,
         67,   68,   69,   70,   71,   72,   73,   74,   75,   76,   77,
         78,   79,   80,   81,   82,   83,   84,   85,   86,   87,   88,
         89,   90,   91,   92,   93,   94,   95,   96,   97,   98,   99,
        100])

In [ ]:
new_vector = matrix.flatten()# it gives a copy
new_vector

array([1000,    2,    3,    4,    5,    6,    7,    8,    9,   10,   11,
         12,   13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
         23,   24,   25,   26,   27,   28,   29,   30,   31,   32,   33,
         34,   35,   36,   37,   38,   39,   40,   41,   42,   43,   44,
         45,   46,   47,   48,   49,   50,   51,   52,   53,   54,   55,
         56,   57,   58,   59,   60,   61,   62,   63,   64,   65,   66,
         67,   68,   69,   70,   71,   72,   73,   74,   75,   76,   77,
         78,   79,   80,   81,   82,   83,   84,   85,   86,   87,   88,
         89,   90,   91,   92,   93,   94,   95,   96,   97,   98,   99,
        100])

In [ ]:
new_vector[0] = 0

In [ ]:
matrix

array([[1000,    2,    3,    4,    5,    6,    7,    8,    9,   10],
       [  11,   12,   13,   14,   15,   16,   17,   18,   19,   20],
       [  21,   22,   23,   24,   25,   26,   27,   28,   29,   30],
       [  31,   32,   33,   34,   35,   36,   37,   38,   39,   40],
       [  41,   42,   43,   44,   45,   46,   47,   48,   49,   50],
       [  51,   52,   53,   54,   55,   56,   57,   58,   59,   60],
       [  61,   62,   63,   64,   65,   66,   67,   68,   69,   70],
       [  71,   72,   73,   74,   75,   76,   77,   78,   79,   80],
       [  81,   82,   83,   84,   85,   86,   87,   88,   89,   90],
       [  91,   92,   93,   94,   95,   96,   97,   98,   99,  100]])

In [ ]:
np.copy(matrix)

array([[1000,    2,    3,    4,    5,    6,    7,    8,    9,   10],
       [  11,   12,   13,   14,   15,   16,   17,   18,   19,   20],
       [  21,   22,   23,   24,   25,   26,   27,   28,   29,   30],
       [  31,   32,   33,   34,   35,   36,   37,   38,   39,   40],
       [  41,   42,   43,   44,   45,   46,   47,   48,   49,   50],
       [  51,   52,   53,   54,   55,   56,   57,   58,   59,   60],
       [  61,   62,   63,   64,   65,   66,   67,   68,   69,   70],
       [  71,   72,   73,   74,   75,   76,   77,   78,   79,   80],
       [  81,   82,   83,   84,   85,   86,   87,   88,   89,   90],
       [  91,   92,   93,   94,   95,   96,   97,   98,   99,  100]])

## Specifiying axis in functions

In [ ]:
#Create a matrix with only zeros values
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
#Create a vector with only zeros values
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.ones(3)

array([1., 1., 1.])

In [ ]:
3*np.ones(3)

array([3., 3., 3.])

In [ ]:
#Identity matrix

np.identity(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
matrix = np.array([[10,2,43],[11,0,33],[0,20,3]])
matrix

array([[10,  2, 43],
       [11,  0, 33],
       [ 0, 20,  3]])

In [ ]:
 matrix.sum()

122

In [ ]:
matrix.sum(axis=0), matrix.sum(axis=1)

(array([21, 22, 79]), array([55, 44, 23]))

In [ ]:
np.around(matrix.mean(axis=1), decimals=2)

array([18.33, 14.67,  7.67])

In [ ]:
matrix.max(axis=0)

array([11, 20, 43])

## Boolean vectors & matrices

In [ ]:
vector = np.array([ True, False, False,  True,  True, True])

In [ ]:
vector.dtype

dtype('bool')

In [ ]:
matrix1= vector[np.newaxis, :]
matrix1.dtype , matrix1

(dtype('bool'), array([[ True, False, False,  True,  True,  True]]))

In [ ]:
matrix.reshape(-1, 2)
matrix

array([[ True, False, False,  True,  True,  True]])

In [ ]:
import numpy as np
matrix = np.arange(21).reshape(3,-1)
matrix 

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20]])

In [ ]:
matrix < 5

array([[ True,  True,  True,  True,  True, False, False],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False]])

In [ ]:
bool_matrix = matrix < 5

In [ ]:
bool_matrix.all()

False

In [ ]:
bool_matrix.any()

True

In [ ]:
bool_matrix.all(axis=1)

array([False, False, False])

In [ ]:
bool_matrix.any(axis=1)

array([ True, False, False])

In [ ]:
# Get the nan value
np.nan

nan

In [ ]:
rain = np.array([[1, 0, np.nan],[3, 2, 1],[np.nan, 2, 3]])
rain

array([[ 1.,  0., nan],
       [ 3.,  2.,  1.],
       [nan,  2.,  3.]])

In [ ]:
#Do my datasets contain a nan value
np.isnan(rain).any()

True