<a href="https://colab.research.google.com/github/hanene2030/numpy/blob/main/5_saving_loading_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Saving & Loading data

In [ ]:
import numpy as np



In [ ]:
data = np.loadtxt("data.txt", delimiter=",")

In [ ]:
data.mean()

14.615384615384615

In [ ]:
data2 = np.loadtxt("data.csv", delimiter=",")
data2


array([[ 1.,  2.,  3.,  4.,  5.],
       [nan, 45., 56.,  1., 40.],
       [ 0., 45., 56., 21., 40.],
       [ 2., 45., 56., 11., 67.],
       [23.,  5., 56., 31., 34.],
       [67., 45., nan, 49., 42.],
       [ 3., 45., 45., 50.,  0.]])

In [ ]:
np.isnan(data2).any()

True

## Save the data

In [ ]:
total_mean =  np.around(np.nanmean(data2))
total_mean

30.0

In [ ]:
np.nan_to_num(data2, copy=False,nan=total_mean)

array([[ 1.,  2.,  3.,  4.,  5.],
       [30., 45., 56.,  1., 40.],
       [ 0., 45., 56., 21., 40.],
       [ 2., 45., 56., 11., 67.],
       [23.,  5., 56., 31., 34.],
       [67., 45., 30., 49., 42.],
       [ 3., 45., 45., 50.,  0.]])

In [ ]:
data2

array([[ 1.,  2.,  3.,  4.,  5.],
       [30., 45., 56.,  1., 40.],
       [ 0., 45., 56., 21., 40.],
       [ 2., 45., 56., 11., 67.],
       [23.,  5., 56., 31., 34.],
       [67., 45., 30., 49., 42.],
       [ 3., 45., 45., 50.,  0.]])

In [ ]:
np.savetxt("new_data.csv", data2, delimiter=",", fmt="%.0f", header="CSV data")

## Load and save numpy object

In [ ]:
#numpy object has .npy
daily_mean = data2.mean(axis=0)

daily_mean

array([18.        , 33.14285714, 43.14285714, 23.85714286, 32.57142857])

In [ ]:
np.save("daily_mean", daily_mean)

In [ ]:
np.load("daily_mean.npy")

array([18.        , 33.14285714, 43.14285714, 23.85714286, 32.57142857])

In [ ]:
np.savez("full", x=daily_mean, y=data2)

In [ ]:
 np.load("full.npz").files


['x', 'y']

In [ ]:
 np.load("full.npz")["x"], np.load("full.npz")["y"]

(array([18.        , 33.14285714, 43.14285714, 23.85714286, 32.57142857]),
 array([[ 1.,  2.,  3.,  4.,  5.],
        [30., 45., 56.,  1., 40.],
        [ 0., 45., 56., 21., 40.],
        [ 2., 45., 56., 11., 67.],
        [23.,  5., 56., 31., 34.],
        [67., 45., 30., 49., 42.],
        [ 3., 45., 45., 50.,  0.]]))