<a href="https://colab.research.google.com/github/hanene2030/numpy/blob/main/7_basic_linear_algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Basic algebra

In [ ]:
import numpy as np

first_v = np.array([1, 3, 34])
second_v = np.array([-11, 5, 0])

first_m = np.array([[1, 3, 34],[5, 10, 0],[11, -3, 4]])
second_m = np.array([[11, 33, 4],[1, 1, 3],[1, 0, 15]])



In [ ]:
# addition , substraction , Scalar multiplication 
first_v + second_v, first_m + second_m ,first_v - second_v, first_m - second_m  ,3* first_v, 3* first_m 

(array([-10,   8,  34]), array([[12, 36, 38],
        [ 6, 11,  3],
        [12, -3, 19]]), array([12, -2, 34]), array([[-10, -30,  30],
        [  4,   9,  -3],
        [ 10,  -3, -11]]), array([  3,   9, 102]), array([[  3,   9, 102],
        [ 15,  30,   0],
        [ 33,  -9,  12]]))

In [ ]:
#Dot product
np.dot(first_v,second_v)


(4, array([[ 48,  36, 523],
        [ 65, 175,  50],
        [122, 360,  95]]))

In [ ]:
def are_orth(v1,v2):
  return np.dot(v1,v2) == 0
are_orth(first_v, second_v)

False

In [ ]:
#Cross product only works for 2 and 3 dim
#if v // => 0,..0
# always ortho on both/all vectors

In [ ]:
from numpy.core.fromnumeric import searchsorted
cross = np.cross(first_v, second_v)
are_orth(cross, first_v), are_orth(cross, second_v), cross

(True, True, array([-170, -374,   38]))

In [ ]:
from numpy import linalg as alg

# Length of a vector
alg.norm(first_v)


34.14674215792775

In [ ]:
alg.norm(first_m)

37.907782842049734

In [ ]:
def angle(v1, v2):
  cos_angle = np.dot(v1,v2)/ (alg.norm(v1) * alg.norm(v1))
  return np.arccos(cos_angle)
angle(first_v, second_v) *180/np.pi,angle(first_v, cross)*180/np.pi

(89.80344462471687, 90.0)

### Matrix operation

In [ ]:
#Matrix product
# If we use Identity matrix =>Does nothing

In [ ]:
first_m @ first_v

array([1166,   35,  138])

In [ ]:
  first_m @ second_m

array([[ 48,  36, 523],
       [ 65, 175,  50],
       [122, 360,  95]])

In [ ]:
#np.matmul = @
np.matmul(first_m , second_m)

array([[ 48,  36, 523],
       [ 65, 175,  50],
       [122, 360,  95]])

In [ ]:
np.identity(3) @ first_m

array([[ 1.,  3., 34.],
       [ 5., 10.,  0.],
       [11., -3.,  4.]])

In [ ]:
#Matrix power
alg.matrix_power(first_m, 4)

array([[155105, -36375, 120870],
       [ 34575,   7900,  95200],
       [ 30705,  -7305, 157370]])

In [ ]:
# Transpose a matrix
display(first_m.T, first_m)

array([[ 1,  5, 11],
       [ 3, 10, -3],
       [34,  0,  4]])

array([[ 1,  3, 34],
       [ 5, 10,  0],
       [11, -3,  4]])

In [ ]:
first_m.transpose()

array([[ 1,  5, 11],
       [ 3, 10, -3],
       [34,  0,  4]])

In [ ]:
# Defining the matrix called my_matrix
my_matrix = np.array([[1, 4, 5], [10, 13, 9], [10, 8, 5]])

# YOURE CODE GOES BELOW HERE!

# The multiplication of the matrix with its transpose
my_matrix_mul_transpose = my_matrix @ my_matrix.T
my_matrix_mul_transpose

array([[ 42, 107,  67],
       [107, 350, 249],
       [ 67, 249, 189]])

## Solving linear systems

In [ ]:
#invertable or not zero=>not invertable
#we need linalg
alg.det(first_m)

-4269.9999999999945

In [ ]:
alg.det(np.eye(5))

1.0

In [ ]:
a = np.array([[1, 2,3],[2,3,4],[1, 1, 1]]) 


In [ ]:
alg.det(a)

0.0

In [ ]:
#inverse matrix
np.around(alg.inv(first_m) @ first_m , decimals=10)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [-0., -0.,  1.]])

In [ ]:
#With one unique solution

In [ ]:
solution = alg.solve(first_m, first_v)
solution


array([ 2.77798595, -1.08899297,  0.04379391])

In [ ]:
first_m @ solution , first_v

(array([ 1.,  3., 34.]), array([ 1,  3, 34]))

In [ ]:
# with no solution 
#alg.solve(a, first_v) =>Error or number very very big

In [ ]:
#with infinetly many solution
#=> We get only one solutio 